server:
  port: 80

spring:
  application:
    name: gateway
  redis:
    host: 47.108.113.58 #Redis服务器地址
    port: 6379 #Redis服务器连接端口
    database: 0 #Redis数据库索引（默认为0）
    timeout: 180000 #连接超时时间（毫秒）
    password: good18882336322

  cloud:
    loadbalancer:
      enabled: true
    nacos:
      discovery:
        server-addr: http://47.108.113.58:8848/ # 注册到Nacos中
    gateway:
      routes:
        - id: gateway-user-service # 路由唯一表示
          uri: lb://user-service # 需要转发的服务，lb表示负载均衡
          predicates:
            - Path=/user-service/** # 转发以user-service开头的请求
          filters:
            - StripPrefix=1 # 删除路径中的user-service
        - id: gateway-post-service
          uri: lb://post-service
          predicates:
            - Path=/post-service/**
          filters:
            - StripPrefix=1
        - id: gateway-auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1
        - id: gateway-file-service
          uri: lb://file-service
          predicates:
            - Path=/file-service/**
          filters:
            - StripPrefix=1
      # 跨域
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:8080"
            allowCredentials: true
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION
