server:
  port: 8002

spring:
  application:
    name: post-service
  redis:
    host: ${SPRING_REDIS_HOST:123.60.154.22}
    port: ${SPRING_REDIS_PORT:6379}
    database: 0 # Redis数据库索引（默认为0）
    timeout: 180000 # 连接超时时间（毫秒）
    password: ${REDIS_PASSWORD:}
  cloud:
    loadbalancer:
      enabled: true
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:http://121.36.241.84:8848/}
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:123.60.154.22}:${DATABASE_PORT:3306}/${DATABASE_NAME:wevote}?characterEncoding=UTF-8
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:Good18882336322}
    ## driver-class-name: com.mysql.cj.jdbc.Driver # 注意：建议使用MySQL 8+的驱动
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com/fizzy/core/entity


#MyBatis使用pageHelper分页
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true