server:
  port: 8002

spring:
  application:
    name: post-service
  redis:
    host: localhost #Redis服务器地址
    port: 6379 #Redis服务器连接端口
    database: 0 #Redis数据库索引（默认为0）
    timeout: 180000 #连接超时时间（毫秒）
  cloud:
    loadbalancer:
      enabled: true
    sentinel:
      transport:
        dashboard: localhost:8849
      datasource:
        flow: #流控规则
          nacos:
            namespace: e8ff47cd-1040-4abe-871c-886af99be1d3
            server-addr: localhost:8848
            dataId: ${spring.application.name}-flow-rules
            groupId: SENTINEL_GROUP
            data-type: json
            rule-type: flow
        degrade:
          nacos:
            namespace: e8ff47cd-1040-4abe-871c-886af99be1d3
            server-addr: localhost:8848
            dataId: ${spring.application.name}-degrade-rules
            groupId: SENTINEL_GROUP
            data-type: json
            rule-type: degrade
    nacos:
      discovery:
        server-addr: http://localhost:8848/
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/we-vote?characterEncoding=UTF-8
    username: root
    password: good18882336322
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com/fizzy/core/entity


#MyBatis使用pageHelper分页
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true