server:
  port: 8003

spring:
  application:
    name: comment-service
  cloud:
    loadbalancer:
      enabled: true
    nacos:
      discovery:
        server-addr: http://localhost:8848/
  datasource:
    url: jdbc:mysql://rm-2vcvh24t0l5f72556.mysql.cn-chengdu.rds.aliyuncs.com:3306/we-vote?characterEncoding=UTF-8
    username: root
    password: Good18882336322
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com/fizzy/core/entity


#MyBatis使用pageHelper分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true