server:
  port: 8010

spring:
  application:
    name: auth-service
  redis:
    host: 47.108.113.58 #Redis服务器地址
    port: 6379 #Redis服务器连接端口
    database: 0 #Redis数据库索引（默认为0）
    timeout: 180000 #连接超时时间（毫秒）
    password: good18882336322
  cloud:
    loadbalancer:
      enabled: true
    nacos:
      discovery:
        server-addr: http://47.108.113.58:8848/
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/we-vote?characterEncoding=UTF-8
    username: root
    password: good18882336322
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com/fizzy/core/entity